# Generated by Django 5.2.5 on 2025-10-21 16:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_order_placed', models.BooleanField(default=False)),
                ('order_number', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodordering.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodordering.user')),
            ],
        ),
    ]
