# Generated by Django 5.2.5 on 2025-10-24 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0004_foodtracking_orderaddress_paymentdelail_review_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentDelail',
            new_name='PaymentDetail',
        ),
        migrations.RenameField(
            model_name='paymentdetail',
            old_name='expire_date',
            new_name='expiry_date',
        ),
    ]
